cytokine_categories <- tibble::tribble(
  ~gene_symbol,   ~category,
  "CCL1",         "CC Chemokines",
  "CCL11",        "CC Chemokines",
  "CCL13",        "CC Chemokines",
  "CCL14",        "CC Chemokines",
  "CCL15",        "CC Chemokines",
  "CCL16",        "CC Chemokines",
  "CCL17",        "CC Chemokines",
  "CCL18",        "CC Chemokines",
  "CCL19",        "CC Chemokines",
  "CCL2",         "CC Chemokines",
  "CCL20",        "CC Chemokines",
  "CCL21",        "CC Chemokines",
  "CCL22",        "CC Chemokines",
  "CCL23",        "CC Chemokines",
  "CCL24",        "CC Chemokines",
  "CCL25",        "CC Chemokines",
  "CCL26",        "CC Chemokines",
  "CCL27",        "CC Chemokines",
  "CCL28",        "CC Chemokines",
  "CCL3",         "CC Chemokines",
  "CCL3L3",       "CC Chemokines",
  "CCL4",         "CC Chemokines",
  "CCL4L2",       "CC Chemokines",
  "CCL5",         "CC Chemokines",
  "CCL7",         "CC Chemokines",
  "CCL8",         "CC Chemokines",
  "CXCL1",        "CXC Chemokines",
  "CXCL10",       "CXC Chemokines",
  "CXCL11",       "CXC Chemokines",
  "CXCL12",       "CXC Chemokines",
  "CXCL13",       "CXC Chemokines",
  "CXCL14",       "CXC Chemokines",
  "CXCL16",       "CXC Chemokines",
  "CXCL17",       "CXC Chemokines",
  "CXCL2",        "CXC Chemokines",
  "CXCL3",        "CXC Chemokines",
  "CXCL5",        "CXC Chemokines",
  "CXCL6",        "CXC Chemokines",
  "CXCL8",        "CXC Chemokines",
  "CXCL9",        "CXC Chemokines",
  "CX3CL1",       "Other Chemokines",
  "XCL1",         "Other Chemokines",
  "XCL2",         "Other Chemokines",
  "CKLF",         "Other Chemokines",
  "CMTM1",        "Other Chemokines",
  "CMTM2",        "Other Chemokines",
  "CMTM3",        "Other Chemokines",
  "CMTM5",        "Other Chemokines",
  "CMTM7",        "Other Chemokines",
  "CMTM8",        "Other Chemokines",
  "GPR15LG",      "Other Chemokines",
  "IFNA1",        "Interferons",
  "IFNA10",       "Interferons",
  "IFNA14",       "Interferons",
  "IFNA16",       "Interferons",
  "IFNA17",       "Interferons",
  "IFNA2",        "Interferons",
  "IFNA21",       "Interferons",
  "IFNA4",        "Interferons",
  "IFNA5",        "Interferons",
  "IFNA6",        "Interferons",
  "IFNA7",        "Interferons",
  "IFNA8",        "Interferons",
  "IFNB1",        "Interferons",
  "IFNE",         "Interferons",
  "IFNG",         "Interferons",
  "IFNK",         "Interferons",
  "IFNL1",        "Interferons",
  "IFNL2",        "Interferons",
  "IFNL3",        "Interferons",
  "IFNL4",        "Interferons",
  "IFNW1",        "Interferons",
  "IL1A",         "Interleukins",
  "IL1B",         "Interleukins",
  "IL1F10",       "Interleukins",
  "IL1RN",        "Interleukins",
  "IL2",          "Interleukins",
  "IL3",          "Interleukins",
  "IL4",          "Interleukins",
  "IL5",          "Interleukins",
  "IL6",          "Interleukins",
  "IL7",          "Interleukins",
  "IL9",          "Interleukins",
  "IL10",         "Interleukins",
  "IL11",         "Interleukins",
  "IL12A",        "Interleukins",
  "IL12B",        "Interleukins",
  "IL13",         "Interleukins",
  "IL15",         "Interleukins",
  "IL16",         "Interleukins",
  "IL17A",        "Interleukins",
  "IL17B",        "Interleukins",
  "IL17C",        "Interleukins",
  "IL17D",        "Interleukins",
  "IL17F",        "Interleukins",
  "IL18",         "Interleukins",
  "IL19",         "Interleukins",
  "IL20",         "Interleukins",
  "IL21",         "Interleukins",
  "IL22",         "Interleukins",
  "IL23A",        "Interleukins",
  "IL24",         "Interleukins",
  "IL25",         "Interleukins",
  "IL26",         "Interleukins",
  "IL27",         "Interleukins",
  "IL31",         "Interleukins",
  "IL32",         "Interleukins",
  "IL33",         "Interleukins",
  "IL34",         "Interleukins",
  "IL36A",        "Interleukins",
  "IL36B",        "Interleukins",
  "IL36G",        "Interleukins",
  "IL36RN",       "Interleukins",
  "IL37",         "Interleukins",
  "TNF",          "TNF Superfamily",
  "LTA",          "TNF Superfamily",
  "LTB",          "TNF Superfamily",
  "FASLG",        "TNF Superfamily",
  "CD40LG",       "TNF Superfamily",
  "TNFSF4",       "TNF Superfamily",
  "TNFSF8",       "TNF Superfamily",
  "TNFSF9",       "TNF Superfamily",
  "TNFSF10",      "TNF Superfamily",
  "TNFSF11",      "TNF Superfamily",
  "TNFSF12",      "TNF Superfamily",
  "TNFSF13",      "TNF Superfamily",
  "TNFSF13B",     "TNF Superfamily",
  "TNFSF14",      "TNF Superfamily",
  "TNFSF15",      "TNF Superfamily",
  "TNFSF18",      "TNF Superfamily",
  "TNFRSF11B",    "TNF Superfamily",
  "TGFB1",        "TGF-b / BMP / GDF",
  "TGFB2",        "TGF-b / BMP / GDF",
  "TGFB3",        "TGF-b / BMP / GDF",
  "BMP1",         "TGF-b / BMP / GDF",
  "BMP2",         "TGF-b / BMP / GDF",
  "BMP3",         "TGF-b / BMP / GDF",
  "BMP4",         "TGF-b / BMP / GDF",
  "BMP5",         "TGF-b / BMP / GDF",
  "BMP6",         "TGF-b / BMP / GDF",
  "BMP7",         "TGF-b / BMP / GDF",
  "BMP8A",        "TGF-b / BMP / GDF",
  "BMP8B",        "TGF-b / BMP / GDF",
  "BMP10",        "TGF-b / BMP / GDF",
  "BMP15",        "TGF-b / BMP / GDF",
  "GDF1",         "TGF-b / BMP / GDF",
  "GDF2",         "TGF-b / BMP / GDF",
  "GDF3",         "TGF-b / BMP / GDF",
  "GDF5",         "TGF-b / BMP / GDF",
  "GDF6",         "TGF-b / BMP / GDF",
  "GDF7",         "TGF-b / BMP / GDF",
  "GDF9",         "TGF-b / BMP / GDF",
  "GDF10",        "TGF-b / BMP / GDF",
  "GDF11",        "TGF-b / BMP / GDF",
  "GDF15",        "TGF-b / BMP / GDF",
  "NODAL",        "TGF-b / BMP / GDF",
  "LEFTY1",       "TGF-b / BMP / GDF",
  "LEFTY2",       "TGF-b / BMP / GDF",
  "INHA",         "TGF-b / BMP / GDF",
  "INHBA",        "TGF-b / BMP / GDF",
  "INHBB",        "TGF-b / BMP / GDF",
  "INHBC",        "TGF-b / BMP / GDF",
  "INHBE",        "TGF-b / BMP / GDF",
  "MSTN",         "TGF-b / BMP / GDF",
  "GREM1",        "TGF-b / BMP / GDF",
  "GREM2",        "TGF-b / BMP / GDF",
  "CER1",         "TGF-b / BMP / GDF",
  "WNT1",         "Wnt Ligands",
  "WNT2",         "Wnt Ligands",
  "WNT2B",        "Wnt Ligands",
  "WNT3",         "Wnt Ligands",
  "WNT3A",        "Wnt Ligands",
  "WNT4",         "Wnt Ligands",
  "WNT5A",        "Wnt Ligands",
  "WNT5B",        "Wnt Ligands",
  "WNT6",         "Wnt Ligands",
  "WNT7A",        "Wnt Ligands",
  "WNT7B",        "Wnt Ligands",
  "WNT8A",        "Wnt Ligands",
  "WNT8B",        "Wnt Ligands",
  "WNT9A",        "Wnt Ligands",
  "WNT9B",        "Wnt Ligands",
  "WNT10A",       "Wnt Ligands",
  "WNT10B",       "Wnt Ligands",
  "WNT11",        "Wnt Ligands",
  "WNT16",        "Wnt Ligands",
  "CSF1",         "Colony Stimulating Factors",
  "CSF2",         "Colony Stimulating Factors",
  "CSF3",         "Colony Stimulating Factors",
  "FLT3LG",       "Colony Stimulating Factors",
  "KITLG",        "Colony Stimulating Factors",
  "EPO",          "Colony Stimulating Factors",
  "THPO",         "Colony Stimulating Factors",
  "LIF",          "IL-6 / gp130 Family",
  "OSM",          "IL-6 / gp130 Family",
  "CNTF",         "IL-6 / gp130 Family",
  "CLCF1",        "IL-6 / gp130 Family",
  "CRLF1",        "IL-6 / gp130 Family",
  "CTF1",         "IL-6 / gp130 Family",
  "EBI3",         "IL-6 / gp130 Family",
  "VEGFA",        "Angiogenic / Growth",
  "FGF2",         "Angiogenic / Growth",
  "NRG1",         "Angiogenic / Growth",
  "NAMPT",        "Angiogenic / Growth",
  "SPP1",         "Angiogenic / Growth",
  "GPI",          "Angiogenic / Growth",
  "GRN",          "Angiogenic / Growth",
  "MIF",          "Angiogenic / Growth",
  "AIMP1",        "Angiogenic / Growth",
  "ADIPOQ",       "Adipokines / Metabolic",
  "GH1",          "Adipokines / Metabolic",
  "FAM3A",        "Adipokines / Metabolic",
  "FAM3B",        "Adipokines / Metabolic",
  "FAM3C",        "Adipokines / Metabolic",
  "FAM3D",        "Adipokines / Metabolic",
  "HMGB1",        "Alarmins / DAMPs",
  "TSLP",         "Alarmins / DAMPs",
  "ALKAL1",       "Misc / Less Characterized",
  "ALKAL2",       "Misc / Less Characterized",
  "AREG",         "Misc / Less Characterized",
  "C17orf99",     "Misc / Less Characterized",
  "C1QTNF4",      "Misc / Less Characterized",
  "C3",           "Misc / Less Characterized",
  "C5",           "Misc / Less Characterized",
  "EDN1",         "Misc / Less Characterized",
  "EDA",          "Misc / Less Characterized",
  "MSMP",         "Misc / Less Characterized",
  "NDP",          "Misc / Less Characterized",
  "PF4",          "Misc / Less Characterized",
  "PF4V1",        "Misc / Less Characterized",
  "PPBP",         "Misc / Less Characterized",
  "SCG2",         "Misc / Less Characterized",
  "SCGB3A1",      "Misc / Less Characterized",
  "SECTM1",       "Misc / Less Characterized",
  "SLURP1",       "Misc / Less Characterized",
  "TAFA5",        "Misc / Less Characterized",
  "THNSL2",       "Misc / Less Characterized",
  "TIMP1",        "Misc / Less Characterized",
  "VSTM1",        "Misc / Less Characterized"
) 